# Generated by Django 2.2.5 on 2020-02-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicApp', '0004_auto_20200224_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donate',
            old_name='image',
            new_name='Image',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='author',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='bookType',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='title',
        ),
        migrations.AddField(
            model_name='donate',
            name='Author',
            field=models.CharField(default=None, max_length=70),
        ),
        migrations.AddField(
            model_name='donate',
            name='Branch',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('CE', 'Computer'), ('EC', 'Electronics and Communication'), ('IC', 'Intrumantation and Control'), ('MET', 'Metallurgy'), ('BM', 'Bio-Medical')], default='IT', max_length=6),
        ),
        migrations.AddField(
            model_name='donate',
            name='Publication',
            field=models.CharField(default=None, max_length=70),
        ),
        migrations.AddField(
            model_name='donate',
            name='Subject',
            field=models.CharField(default=None, max_length=70),
        ),
        migrations.AddField(
            model_name='donate',
            name='Subject_code',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='donate',
            name='Year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=4),
        ),
    ]
